---
services:
  bind9:
    hostname: ${COMPOSE_PROJECT_NAME}
    domainname: ${LOCAL_DOMAIN}
    container_name: ${COMPOSE_PROJECT_NAME}
    image: internetsystemsconsortium/bind9:${BIND_TAG}
    restart: unless-stopped
    volumes:
      - /appdata/${COMPOSE_PROJECT_NAME}/conf:/etc/bind
      - /appdata/${COMPOSE_PROJECT_NAME}/cache:/var/cache/bind
      - /appdata/${COMPOSE_PROJECT_NAME}/lib:/var/lib/bind
      - /appdata/${COMPOSE_PROJECT_NAME}/log:/var/log
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${THIS_IP}

networks:
  net1:
    external: true
    name: ${LAN_NAME}
